### ISSUE TITLE
维度不匹配

### ISSUE THREAD

**Issue by LLSL240** [ivanhe123/RpBERT-GCN-NER#1]
RuntimeError: The size of tensor a (514) must match the size of tensor b (512) at non-singleton dimension 1

**Comment by ivanhe123** [comment]
Please send the whole error, the output before the runtime error.

**Comment by ivanhe123** [comment]
Also, this model will not work with Chinese Datasets.
Is your dataset a Chinese dataset?
If so, there need to be minor changes.

**Comment by LLSL240** [comment]
Yes,my Datasets is Chinese. I have modified bert's pre-training model and the English model in SpaCy library. Can you tell me what other changes need to be made？

**Comment by liusenling** [comment]
![Uploading 微信图片_20240409012747.jpg…]()

**Comment by ivanhe123** [comment]
Can you please send me your chinese dataset? The test dataset is ok.
I will check if the format is correct.

**Comment by ivanhe123** [comment]
Also copy the whole error that was outputed into the console and paste it here.
I can't see the image.

**Comment by liusenling** [comment]
0%|          | 0/2500 [01:27<?, ?it/s]
Traceback (most recent call last):
  File "E:\多模态医疗实体识别\RpBERT-GCN-NER-main\train.py", line 63, in <module>
    ner_loss = train(ner_train_loader, model, optimizer, task='ner')
  File "E:\多模态医疗实体识别\RpBERT-GCN-NER-main\utils.py", line 32, in train
    loss, _ = getattr(model, f'{task}_forward')(batch)
  File "E:\多模态医疗实体识别\RpBERT-GCN-NER-main\model.py", line 226, in ner_forward
    outputs = self._bert_forward_with_image(inputs, datas)
  File "E:\多模态医疗实体识别\RpBERT-GCN-NER-main\model.py", line 170, in _bert_forward_with_image
    return self.encoder_t(
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Anaconda\envs\pytorch\lib\site-packages\transformers\models\bert\modeling_bert.py", line 1006, in forward
    embedding_output = self.embeddings(
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Anaconda\envs\pytorch\lib\site-packages\transformers\models\bert\modeling_bert.py", line 238, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (561) must match the size of tensor b (512) at non-singleton dimension 1

**Comment by LLSL240** [comment]
[test.txt](https://github.com/ivanhe123/RpBERT-GCN-NER/files/14912098/test.txt)

**Comment by ivanhe123** [comment]
the format of the dataset should be:
WORD/tEntity.
Yours is:
WORD Entity

Also, for spacy parser, it parses not word by word, but a group of chinese characters, for an example, if it parses this sentence:
作为语言而言，为世界使用人数最多的语言，目前世界有五分之一人口做为母语。
It parses as:
作为 ADP case
语言 NOUN nmod:prep
而言 PART case
， PUNCT punct
为 ADP case
世界 NOUN compound:nn
使用 NOUN compound:nn
人数 NOUN nsubj
最多 VERB amod
的 PART mark
语言 NOUN nmod:prep
， PUNCT punct
目前 NOUN nmod:tmod
世界 NOUN dep
有 VERB ROOT
五分之一 NUM dep
人口 NOUN dobj
做为 VERB conj
母语 NOUN dobj
。 PUNCT punct

So there is something wrong with the dataset overall.

**Comment by LLSL240** [comment]
E:\Anaconda\envs\pytorch\python.exe E:/多模态医疗实体识别/RpBERT-GCN-NER-main/train.py
  5%|▌         | 127/2500 [07:42<2:24:03,  3.64s/it]
Traceback (most recent call last):
  File "E:\多模态医疗实体识别\RpBERT-GCN-NER-main\train.py", line 63, in <module>
    ner_loss = train(ner_train_loader, model, optimizer, task='ner')
  File "E:\多模态医疗实体识别\RpBERT-GCN-NER-main\utils.py", line 32, in train
    loss, _ = getattr(model, f'{task}_forward')(batch)
  File "E:\多模态医疗实体识别\RpBERT-GCN-NER-main\model.py", line 224, in ner_forward
    outputs = self._bert_forward_with_image(inputs, datas)
  File "E:\多模态医疗实体识别\RpBERT-GCN-NER-main\model.py", line 170, in _bert_forward_with_image
    return self.encoder_t(
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Anaconda\envs\pytorch\lib\site-packages\transformers\models\bert\modeling_bert.py", line 1006, in forward
    embedding_output = self.embeddings(
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Anaconda\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Anaconda\envs\pytorch\lib\site-packages\transformers\models\bert\modeling_bert.py", line 238, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (514) must match the size of tensor b (512) at non-singleton dimension 1

进程已结束,退出代码1

**Comment by ivanhe123** [comment]
There's a way around it, fortunately.
We will not parse the words using dependency parsing, rather, connect all words together.
This will take some time.
Please fork a copy of this github repository, rename it to "Chinese RpBERT-GCN-NER" and send me a link towards the repository.

**Comment by ivanhe123** [comment]
just send the link here

**Comment by LLSL240** [comment]
I changed the code reading code to text, label = line.split(" ") is also not OK?

**Comment by ivanhe123** [comment]
it is ok.
The dataset format is ok now, but the dataset overall is not suited for this application.
There's a way around it, fortunately.
We will not parse the words using dependency parsing, rather, connect all words together.
This will take some time.
Please fork a copy of this github repository, rename it to "Chinese RpBERT-GCN-NER" and send a link to the repository in this issue.

**Comment by LLSL240** [comment]
[https://github.com/liusenling/Chinese-RpBERT-GCN-NER](url)

**Comment by ivanhe123** [comment]
send me a link in which I can download all your training, dev, test and image assets.

**Comment by LLSL240** [comment]
Sorry, the data cannot be shared for the time being because of privacy concerns.

**Comment by ivanhe123** [comment]
Then Sorry, I cannot help you without knowing the dataset.
You can change the edge_index function so that each chinese character connects to each other in the graph.

**Comment by LLSL240** [comment]
Thank you for your answers and help
